In [2]:
import pandas as pd
movies=pd.read_csv("../data/CSV_Datasets/movies_data.csv")
movies.head(3)
movies.shape
movies.head(3)
movies.sort_values(by='Votes',inplace=True,ascending=False)
movies.head(10)

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
3088,Life of Pi,2012,127,"Adventure, Drama, Fantasy",7.9,591417,Ang Lee,Suraj Sharma,Irrfan Khan,Adil Hussain
44,3 Idiots,2009,170,"Comedy, Drama",8.4,357889,Rajkumar Hirani,Aamir Khan,Madhavan,Mona Singh
3094,Lion,2016,118,"Biography, Drama",8.0,220526,Garth Davis,Dev Patel,Nicole Kidman,Rooney Mara
1823,Gandhi,1982,191,"Biography, Drama, History",8.0,220118,Richard Attenborough,Ben Kingsley,John Gielgud,Rohini Hattangadi
5096,The Darjeeling Limited,2007,91,"Adventure, Comedy, Drama",7.2,185127,Wes Anderson,Owen Wilson,Adrien Brody,Jason Schwartzman
3092,Like Stars on Earth,2007,165,"Drama, Family",8.4,175810,Aamir Khan,Amole Gupte,Darsheel Safary,Aamir Khan
4023,PK,2014,153,"Comedy, Drama, Musical",8.1,168150,Rajkumar Hirani,Aamir Khan,Anushka Sharma,Sanjay Dutt
1276,Dangal,2016,161,"Action, Biography, Drama",8.4,165074,Nitesh Tiwari,Aamir Khan,Sakshi Tanwar,Fatima Sana Shaikh
4200,Radhe,2021,135,"Action, Crime, Thriller",1.8,162455,Prabhu Deva,Salman Khan,Disha Patani,Randeep Hooda
1436,Dil Bechara,2020,101,"Comedy, Drama, Romance",6.6,117377,Mukesh Chhabra,Sushant Singh Rajput,Sanjana Sanghi,Sahil Vaid

In [3]:
Indian_movies=pd.read_csv("../data/CSV_Datasets/indian movies.csv")
Indian_movies.head(3)
Indian_movies['Language'].unique()

array(['hindi', 'urdu', 'bengali', 'telugu', 'nepali', 'sanskrit',
       'tamil', 'kannada', 'marathi', 'malayalam', 'bhojpuri', 'gujarati',
       'oriya', 'punjabi', 'assamese', 'rajastani', 'kashmiri', 'konkani',
       'tulu'], dtype=object)

In [4]:
Indian_movies.head()
Indian_movies.shape
Indian_movies.nunique()

ID             46106
Movie Name     42442
Year             579
Timing(min)      259
Rating(10)        92
Votes           2951
Genre            718
Language          19
dtype: int64

In [5]:
import numpy as np
def summ(lst):
    ans=''
    for i in lst:
        ans+=i
    return ans
print(Indian_movies.info())
unq=Indian_movies['Votes'].unique()
print("\n",unq)
Indian_movies['Votes'].replace('-','0',inplace=True)
Indian_movies['Votes'].replace('$5.16M','0',inplace=True)
unq=Indian_movies['Votes'].unique()
print("\n",unq)
# print(type(Indian_movies['Votes'].str.split(',')))
Indian_movies['Votes']=Indian_movies['Votes'].str.split(',')
Indian_movies['Votes']=pd.Series([summ(i) for i in Indian_movies['Votes']])
# Indian_movies['Votes']=Indian_movies['Votes'].apply(lambda x:sum(x))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50602 entries, 0 to 50601
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           50602 non-null  object
 1   Movie Name   50602 non-null  object
 2   Year         49041 non-null  object
 3   Timing(min)  50602 non-null  object
 4   Rating(10)   50602 non-null  object
 5   Votes        50602 non-null  object
 6   Genre        50602 non-null  object
 7   Language     50602 non-null  object
dtypes: object(8)
memory usage: 3.1+ MB
None

 ['-' '1,892' '20' ... '20,587' '1,923' '16,102']

 ['0' '1,892' '20' ... '20,587' '1,923' '16,102']

C:\Users\panka\AppData\Local\Temp\ipykernel_17356\1419074825.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Indian_movies['Votes'].replace('-','0',inplace=True)
C:\Users\panka\AppData\Local\Temp\ipykernel_17356\1419074825.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Indian_movies['Votes'].replace('$5.16M','0',inplace=True)

In [6]:
Indian_movies['Votes']=Indian_movies['Votes'].astype(np.int64)
Indian_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50602 entries, 0 to 50601
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           50602 non-null  object
 1   Movie Name   50602 non-null  object
 2   Year         49041 non-null  object
 3   Timing(min)  50602 non-null  object
 4   Rating(10)   50602 non-null  object
 5   Votes        50602 non-null  int64
 6   Genre        50602 non-null  object
 7   Language     50602 non-null  object
dtypes: int64(1), object(7)
memory usage: 3.1+ MB

In [11]:
print(Indian_movies[Indian_movies['Language']=='hindi'].shape[0])
Indian_movies[Indian_movies['Language']=='hindi'].sort_values(by='Votes',ascending=False).head(15)
genre=input('Enter the kind of movie you likes :')
Indian_movies.replace('-','0',inplace=True)
Indian_movies[[genre in lst for lst in Indian_movies['Genre'].str.split(', ')]].sort_values(by='Votes',ascending=False)

14350

,ID,Movie Name,Year,Timing(min),Rating(10),Votes,Genre,Language
35212,tt1187043,3 Idiots,2009,170 min,8.4,351187,"Comedy, Drama",hindi
11438,tt0838221,The Darjeeling Limited,2007,91 min,7.2,183367,"Adventure, Comedy, Drama",punjabi
45327,tt2338151,PK,2014,153 min,8.1,165617,"Comedy, Drama, Musical",hindi
13170,tt5462602,The Big Sick,2017,120 min,7.5,123297,"Comedy, Drama, Romance",oriya
13408,tt5462602,The Big Sick,2017,120 min,7.5,123297,"Comedy, Drama, Romance",urdu
...,...,...,...,...,...,...,...,...
34963,tt0213092,Moti Mahal,1952,0,0,0,"Comedy, Drama, Fantasy",hindi
19212,tt2349700,Bhagaude,2012,94 min,0,0,"Comedy, Drama",hindi
19289,tt4718678,I Love Desi,2015,0,0,0,"Comedy, Romance",hindi
268,0,Paradise Street,NaN,0,0,0,"Comedy, Romance, Thriller",hindi
27800,tt13626286,Anjana 2007,2007,74 min,0,0,"Comedy, Romance",assamese